# Generated by Django 4.1.7 on 2023-03-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_alter_event_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.CharField(
                choices=[
                    ("TO DO", "To do"),
                    ("IN PROGRESS", "In progress"),
                    ("FINISHED", "Finished"),
                ],
                default="TO DO",
                max_length=25,
            ),
        ),
    ]
