# Generated by Django 4.1.7 on 2023-02-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['id']},
        ),
    ]
